### ISSUE TITLE
 when Upload image set required failed

### ISSUE THREAD

**Issue by Oaufi** [yesworld/plugin-wp-optimize-image#14]
Hi , when we set the Upload image as required we don’t get the attachments Via mail when we remove the required we get the attachments please fix

**Comment by Aphyxia** [comment]
The underlying problem is somewhere else but I fixed it by adding a check to line 114 in frontend/index.php
$shotPath = explode(self::UPLOAD_FOLDER . '/', $file)[1];
to
$shotPath = strpos($file, self::UPLOAD_FOLDER . '/') !== false ? explode(self::UPLOAD_FOLDER . '/', $file)[1] : $file;

It seems when the field is required, $file does not have the upload folder part and that breaks the attaching process.

**Comment by Oaufi** [comment]
> The underlying problem is somewhere else but I fixed it by adding a check to line 114 in frontend/index.php $shotPath = explode(self::UPLOAD_FOLDER . '/', $file)[1]; to $shotPath = strpos($file, self::UPLOAD_FOLDER . '/') !== false ? explode(self::UPLOAD_FOLDER . '/', $file)[1] : $file;
> 
> It seems when the field is required, $file does not have the upload folder part and that breaks the attaching process.

Thanks, yes now it is working as expected.

**Comment by bruklig** [comment]
@Oaufi Thank you for finding that issue and letting us know.

@Aphyxia Thank you for finding a working solution, we'll add it to the next release of the plugin.

**Comment by yesworld** [comment]
Thanks guys! I just uploaded a new version. 
https://wordpress.org/plugins/images-optimize-and-upload-cf7/
